services:
  ocr-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./extracted_texts:/app/extracted_texts
      - ./original_pdfs:/app/original_pdfs
    environment:
      - PYTHONPATH=/app
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
